name: Quality Checks
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        django-version: ['3.2', '3.1', '3.0', '2.2', '2.1', '2.0']
        python-version: ['3.7', '3.8', '3.9']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'setup.py'
      - name: Install Python Dependencies
        run: |
            pip install --upgrade pip wheel
            pip install Django~=${{ matrix.django-version }}
            python setup.py install
      - name: Run tests
        run: python run_tests.py
