name: Quality Checks
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        django-version: ["4.2", "5.0"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "pyproject.toml"

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip wheel
          pip install "Django==${{ matrix.django-version }}"
          pip install -e .

      - name: Run tests
        run: |
          pytest django_auth_lti/tests -vv
